config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'ranking#index'
  match 'ranking/movie(/:id)'  => 'ranking#show' , :via => :get, as: :movie
  get 'users/new/complete' => 'users#complete'
  
  
  get 'users/new/addmovie' => 'users#addmovie'
  get 'ranking/28' => 'ranking#show28'
  get 'ranking/29' => 'ranking#show29'
  get 'ranking/30' => 'ranking#show30'
  get 'ranking/31' => 'ranking#show31'
  get 'ranking/01' => 'ranking#show01'
  get 'ranking/02' => 'ranking#show02'
  get 'ranking/03' => 'ranking#show03'
  get 'ranking/04' => 'ranking#show04'
  get 'ranking/05' => 'ranking#show05'
  

end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :movie, MovieUploader
    validates_presence_of :time, :message => "は必須項目です。"
    validates_presence_of :name, :message => "は必須項目です。"
    validates_uniqueness_of :name, :message => "が重複しています。"
    
#ユーザー名による絞り込み 
scope :get_by_name, ->(name) {
where("name like ?", "%#{name}%")
}

def self.get_day(day)
  where(created_at: Time.new(day).all_day)
end

#日付による絞り込み
#scope :get_by_day, ->(day) { where("created_at ?", "Date.new{day}.beginning_of_day..Date.new{day}.end_of_day")}
 scope :get_by_day, ->(day) { where("created_at ?",  "Time.new(day).all_day")}
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
    def index
     @users = User.order('time ASC').page(params[:page])
     
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    
    def show28
        range = Date.new(2017,10,28).beginning_of_day..Date.new(2017,10,28).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    
    def show29
        range = Date.new(2017,10,29).beginning_of_day..Date.new(2017,10,29).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show30
        range = Date.new(2017,10,30).beginning_of_day..Date.new(2017,10,30).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show31
        range = Date.new(2017,10,31).beginning_of_day..Date.new(2017,10,31).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show01
        range = Date.new(2017,11,01).beginning_of_day..Date.new(2017,11,01).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show02
        range = Date.new(2017,11,02).beginning_of_day..Date.new(2017,11,02).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show03
        range = Date.new(2017,11,03).beginning_of_day..Date.new(2017,11,03).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show04
        range = Date.new(2017,11,04).beginning_of_day..Date.new(2017,11,04).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
    def show05
        range = Date.new(2017,11,05).beginning_of_day..Date.new(2017,11,05).end_of_day
        @users = User.where(created_at: range).order('created_at ASC').page(params[:page]).per(20)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with :name => "tms", :password => "fRd27e"

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.order('id ASC').page(params[:page]).per(20)
    
     if params[:name].present?
       @users = @users.get_by_name params[:name]
     end
     
     if params[:allow].present?
       @users = @users.where(:allow => true)
     end
     
     if params[:createday].present?
     time = Time.parse(params[:createday]).all_day
     @users = @users.where(:created_at => time)
     end
     
     if params[:movieexist].present?
       @users = @users.where(:movie => nil)
     end
  end
  


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_new_complete_path, notice: '登録完了' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :back, notice: '更新完了' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '削除完了' }
      format.json { head :no_content }
    end
  end
  
 
  def complete
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :time, :movie, :remove_movie, :allow, :bestlap)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCHAEFFLER TMS</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ranking/_commingsoon.html.erb
<div class="comsoon">
    
    
    
    <%= image_tag("lucasdemo.png", :class => "comsoonimg") %>
   

<p>動画公開までしばらくお待ちください。</p>

</div>

app/views/ranking/_logo.html.1.erb
<div calss="logos">
    <%= image_tag("Schaeffler.png",:size => "211x25",:align => "right", :class => "logoimg") %>
</div>

app/views/ranking/_logo.html.erb
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-59f03120f8796b72"></script>

     <nav class="navbar navbar-default">
         <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
             
            </button>
              
            <a class="navbar-brand" id="navbar-brand1" href="https://www.schaeffler.co.jp/content.schaeffler.jp/ja/index.jsp" target="_blank"><%= image_tag 'Schaeffler.png', :height => "100%" %></a>
          </div>
            
           
          <div id="navbar" class="navbar-collapse collapse">
              
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href=<%= root_path %>>Home</a></li>

                
                
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Results<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li class="divider"></li>
                  <li class="dropdown-header">日別ドライバーリザルト</li>
                  <li><a href=<%= ranking_28_path %>>10/28</a></li>
                  <li><a href=<%= ranking_29_path %>>10/29</a></li>
                  <li><a href=<%= ranking_30_path %>>10/30</a></li>
                  <li><a href=<%= ranking_31_path %>>10/31</a></li>
                  <li><a href=<%= ranking_01_path %>>11/01</a></li>
                  <li><a href=<%= ranking_02_path %>>11/02</a></li>
                  <li><a href=<%= ranking_03_path %>>11/03</a></li>
                  <li><a href=<%= ranking_04_path %>>11/04</a></li>
                  <li><a href=<%= ranking_05_path %>>11/05</a></li>
                  
                    
                
                </ul>
              </li>
            </ul>
            
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/ranking/_lucas.html.erb
<div class="lucasprofile">
    <%= image_tag("lucas.jpg", :class => "lucasimg", :hspace => "20px", :vspace => "20px") %>
    <br />
    <h3>ルーカス・ディ・グラッシ</h3><br />
       <p>1984年8月11日生<br />
       ブラジル・サンパウロ出身<br />
       身長179cm、体重74kg<br />
       アプト・シェフラー・アウディ・スポーツ所属<br />
       フォーミュラEシーズン3ドライバーズチャンピオン</p>
</div>

app/views/ranking/_lucasvideo.html.erb
<div class="videolucas">
  <h5>オンボード画面</h5>
  <iframe
  src="https://www.youtube.com/embed/wp74WB08eb4?rel=0&showinfo=0"
  frameborder="0" allowfullscreen>
  </iframe>
  <!--<h5>俯瞰画面</h5>
   <iframe
  src="https://www.youtube.com/embed/53PWWda4NiU?rel=0&showinfo=0"
  frameborder="0" allowfullscreen>
  </iframe>-->

    <h4>タイム </h4>
    <h3><strong>39.625</strong></h3>
    
</div>

app/views/ranking/_resulttable.html.erb
 <div class="c-result-table">
<table class="ctable">
  <thead>
        <tr>
      <th width="20%">Date</th>
      <th width="55%">Driver</th>
      <th width="20%">Time</th>
    </tr>
  </thead>
  <tbody>
       <% @users.each do |user| %>
  
    <tr><td class="rank"><%= user.created_at.strftime("%m/%d %H:%M") %></td><td><%= link_to_if(user.movie.present?, user.name, movie_path(user)) %></td><td><%= user.time %></td></tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<div class="pagenater">
<%= paginate @users %>
</div>

app/views/ranking/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
    
  </head>
  <body>
   <%= render 'logo' %>
<div>
<div class="a-head-title">
 <h1>タイムトライアル　フォーミュラEにチャレンジ！ </h1>
</div>
</div>
<div class="a-head-image">
</div>

<h2 class="b-lucas-title"><strong>ルーカスに挑戦！</strong></h2>

<div class="b-lucas">
 <%= render 'lucas' %>
 <h3 class="b-lucas-title"><strong>ルーカスアタック映像</strong></h3>
 
 <%= render 'lucasvideo' %>
 <div class="addthis_inline_share_toolbox_wa2q" id="videoshare"></div>
</div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Top 10 Drivers </h2>
 </div>
 <div class="c-result-table">
<table class="ctable">
  <thead>
        <tr>
      <th width="5%">Pos</th>
      <th width="20%">Date</th>
      <th width="55%">Driver</th>
      <th width="20%">Time</th>
    </tr>
  </thead>
  <tbody>
       <% @users.each.with_index(1) do |user, index| %>
  
    <tr><td class="rank"><%= "#{index}" %></td><td><%= user.created_at.strftime("%m/%d %H:%M") %></td> <td><%= link_to_if(user.movie.present?, user.name, movie_path(user)) %></td><td><%= user.time %></td></tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>



<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> All Results </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/29', ranking_29_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '10/31', ranking_31_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/03', ranking_03_path %></li>
<li><%= link_to '11/04', ranking_04_path %></li>
<li><%= link_to '11/05', ranking_05_path %></li>

</ul>
</div>

</div>
</div>
<div class="addthis_inline_share_toolbox_wa2q"></div>

<%= render 'dropup' %>

</body>
</html>

app/views/ranking/show.html.erb
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
    
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%= render 'logo' %>

<div class="a-head-title">
    <h1>Play Movie </h1>
</div>
<div class="ca-image">
</div>

<div class="ca-video">
 <div class="ca-video-content">
    <div class="ca-video-title">
        <h2>Driver: <%= @user.name %></h2>
    </div>
    <div class="video">
     <%= video_tag @user.movie_url.to_s, :width => "100%", :controls => true %>
     </div>
  </div>

  <div class="ca-sns">
     <div class="addthis_inline_share_toolbox_wa2q"></div>
  </div>


<%= render 'dropup' %>

 
</body>

app/views/ranking/show03.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
    <%= render 'logo' %>

<div class="ba-head">
    <div class="a-head-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results of 11/03</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Days </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/29', ranking_29_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '10/31', ranking_31_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/04', ranking_04_path %></li>
<li><%= link_to '11/05', ranking_05_path %></li>

</ul>
</div>
</div>
</div>

<%= render 'dropup' %>
</body>
</html>

app/views/ranking/show04.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
    <%= render 'logo' %>

<div class="ba-head">
    <div class="a-head-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results of 11/04</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Days </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/29', ranking_29_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/03', ranking_03_path %></li>
<li><%= link_to '11/05', ranking_05_path %></li>

</ul>
</div>
</div>
</div>

<%= render 'dropup' %>
</body>
</html>

app/views/ranking/show05.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
    <%= render 'logo' %>

<div class="ba-head">
    <div class="a-head-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results of 11/05</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Days </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/29', ranking_29_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '10/31', ranking_31_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/03', ranking_03_path %></li>
<li><%= link_to '11/04', ranking_04_path %></li>


</ul>
</div>
</div>
</div>

<%= render 'dropup' %>
</body>
</html>

app/views/ranking/show29.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
    <%= render 'logo' %>

<div class="ba-head">
    <div class="a-head-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results of 10/29</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Days </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '10/31', ranking_31_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/03', ranking_03_path %></li>
<li><%= link_to '11/04', ranking_04_path %></li>
<li><%= link_to '11/05', ranking_05_path %></li>

</ul>
</div>
</div>
</div>

<%= render 'dropup' %>
</body>
</html>

app/views/ranking/show31.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
    <%= render 'logo' %>

<div class="ba-head">
    <div class="a-head-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results of 10/31</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Days </h2>
</div>

<div class="item-list">
<ul>
<li><%= link_to '10/28', ranking_28_path %></li>
<li><%= link_to '10/29', ranking_29_path %></li>
<li><%= link_to '10/30', ranking_30_path %></li>
<li><%= link_to '11/01', ranking_01_path %></li>
<li><%= link_to '11/02', ranking_02_path %></li>
<li><%= link_to '11/03', ranking_03_path %></li>
<li><%= link_to '11/04', ranking_04_path %></li>
<li><%= link_to '11/05', ranking_05_path %></li>

</ul>
</div>
</div>
</div>

<%= render 'dropup' %>
</body>
</html>

app/views/ranking/showss.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
  </head>

   
<body>
<div class="ba-head">
    <div class="ba-title">
    <h1>Results</h1>
    </div>
</div>

<div class="ba-head-image">
  </div>

<div class="c-result">
 <div class="c-result-content">
 <div class="c-result-title">
  <h2>Results on 11/03</h2>
 </div>
    <% if @users.blank? %>
    <div class="c-nodata"><p>ドライバーが登録されていません。</p></div>
   <% else %>
<%= render 'resulttable' %>
   <% end %>
 </div>
 </div>
 
<div class="d-result">
<div class="d-result-content">
<div class="d-result-title">
<h2> Other Day </h2>
</div>

<table class="d-result-table">
<tbody>
<tr>
<th><%= link_to '10/28', ranking_28_path %></th>
<th><%= link_to '10/29', ranking_29_path %></th>
<th><%= link_to '10/30', ranking_30_path %></th>
<th><%= link_to '11/01', ranking_01_path %></th>
<th><%= link_to '11/02', ranking_02_path %></th>
<th><%= link_to '11/03', ranking_03_path %></th>
<th><%= link_to '11/04', ranking_04_path %></th>
<th><%= link_to '11/05', ranking_05_path %></th>
</tr>
</tbody>
</table>
</div>
</div>


</body>
</html>

app/views/users/_logo.html.erb
<div calss="logos">
    <%= image_tag("Schaeffler.png",:size => "211x25",:align => "right 30px", :class => "logoimg") %>
</div>

app/views/users/addmovie.html.erb
<%= form_tag({action: 'uploadmovie'}, {method: 'patch'}) do %>
        
    <%= label_tag :user, :movie, "upload" %><br>
    <%= file_field_tag :movie, @user.movie %>
   
    <%= submit_tag "post" %>
<% end %>

app/views/users/complete.html.erb
  <div class="schimg">
  <%= render 'logo' %>
  </div>
<div class="container">
<p id="notice"><%= notice %></p>
<div class="showtitle">
<h1>Thank you for playing!</h1>
</div>

<div class="linknewdriver">
<p><%= link_to 'New Driver', new_user_path %></p>
</div>
</div>

app/views/users/edit.html.erb
<body>
<p id="notice"><%= notice %></p>
<div class="editcontent">
<h1>Editing User</h1>

<%= render 'form' %>


<%= link_to 'Back', users_path %>
</div>
</body>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

<h1>管理画面</h1>



<div id="search"> 
<%= form_tag(users_path, method: "get") do %>
<%= label_tag :name, "Name  " %>
<%= text_field_tag :name, params[:name] %><br>
<%= label_tag :createday, "登録日" %>
<%= date_field_tag :createday, Date.today %>
<%= label_tag :allow, "動画公開可のみ" %>
<%= check_box_tag :allow, true, false %>
<%= label_tag :movieexist, "動画未アップのみ" %>
<%= check_box_tag :movieexist, true, false %>
<%= submit_tag "検索" %>
<% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th width="5%">ID</th>
      <th width="10%">Day</th>
      <th width="30%">Name</th>
      <th width="10%">Time</th>
      <th WIdth="5%">BestLap</th>
      <th width="10%">動画公開可否</th>
      <th width="5%">動画有無</th>
      <th width="25%"; colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.created_at.strftime("%m月%d日 %H時%M分") %></td>
        <td><%= user.name %></td>
        <td><%= user.time %></td>
        <td><%= user.bestlap %></td>
        <td><%= user.allow ? '可' : '不可' %></td>
        <td><%= user.movie? ? 'UP済' : '未UP' %></td>
        <td><%= link_to '編集', edit_user_path(user), :target=>["_blank"] %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除しますか？?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div><%= paginate @users %></div>

<%= link_to 'New Driver', new_user_path %>
</div>

app/views/users/show.html.erb
<div class="shownotice">
<p id="notice"><%= notice %></p>
</div>
<div class="showinfo">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @user.time %>
</p>
</div>


<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '管理画面', users_path %>